[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/thebearjew/plantbook"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Internal
common = { version = "0.1.0", path = "../common" }

# External
yew = {git = "https://github.com/yewstack/yew", branch = "master"} # Yew @ next
yew-router = { git = "https://github.com/yewstack/yew", branch="master" }
yewdux = { git = "https://github.com/intendednull/yewdux.git" }
yewdux-functional = { git = "https://github.com/intendednull/yewdux.git" }
gloo-utils = "0.1"
rand = "0.8.4"
getrandom = { version = "0.2.3", features = ["js"] } # This is a dependency of rand which requries the js feature to work
serde = { version = "^1.0", features = [ "derive" ] }
chrono = { version = "0.4.19", features = [ "serde", "wasmbind" ] } # Chrono for date diffing -> consider changing this as it is no longer maintained
log = "0.4.14"
wasm-logger = "0.2" # Logging for WASM applications
wasm-bindgen = "0.2.67"
