[package]
name = "backend"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/thebearjew/plantbook"

[dependencies]
axum = "^0.3"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1" # Also known as loggingtracing = "0.1" # Also known as logging
serde = { version = "^1.0", features = [ "derive" ] }
tracing-subscriber = { version="0.3", features = ["env-filter"] }
