[package]
name = "common"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/thebearjew/plantbook"

[dependencies]
serde = { version = "^1.0", features = [ "derive" ] }
validator = { version = "0.12", features = ["derive"] }
chrono = { version = "0.4.19", features = [ "serde" ] }
uuid = { version = "0.8", features = ["serde", "v4"] }
